// Professional Wikipedia-style historical illustrations with 8 completely different diagram types
export const generateProfessionalDiagram = (query, index) => {
  const lowerQuery = query.toLowerCase();
  
  // Generate unique seed from query
  const seed = query.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
  const diagramType = seed % 8;
  
  // Determine theme
  let theme = 'historical';
  if (lowerQuery.includes('war') || lowerQuery.includes('battle') || lowerQuery.includes('world war')) theme = 'war';
  else if (lowerQuery.includes('art') || lowerQuery.includes('renaissance') || lowerQuery.includes('paint')) theme = 'art';
  else if (lowerQuery.includes('empire') || lowerQuery.includes('kingdom') || lowerQuery.includes('mughal') || lowerQuery.includes('roman')) theme = 'empire';
  else if (lowerQuery.includes('pyramid') || lowerQuery.includes('egypt') || lowerQuery.includes('ancient') || lowerQuery.includes('greece')) theme = 'ancient';
  else if (lowerQuery.includes('temple') || lowerQuery.includes('church') || lowerQuery.includes('mosque')) theme = 'religion';
  
  const colors = {
    ancient: { primary: '#8B7355', accent: '#D4AF37', tertiary: '#CD853F' },
    war: { primary: '#2C3E50', accent: '#7F8C8D', tertiary: '#34495E' },
    art: { primary: '#8E44AD', accent: '#3498DB', tertiary: '#E74C3C' },
    empire: { primary: '#8B0000', accent: '#DAA520', tertiary: '#4B0082' },
    religion: { primary: '#5D4E6D', accent: '#1F4788', tertiary: '#7E7F9A' },
    historical: { primary: '#4A5568', accent: '#667eea', tertiary: '#764ba2' }
  };
  
  const c = colors[theme];
  
  const diagramTypes = ['timeline', 'hierarchy', 'flowchart', 'network', 'pyramid', 'circular', 'comparison', 'process'];
  
  const selectedType = index === 0 ? diagramTypes[diagramType] : diagramTypes[(diagramType + 4) % 8];
  const variation = index === 0 ? seed : seed + 100;
  
  const generators = {
    timeline: () => {
      const h1 = 40 + (variation % 30), h2 = 60 + ((variation * 2) % 35), h3 = 80 + ((variation * 3) % 25), h4 = 50 + ((variation * 4) % 40);
      return `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 350"><rect width="500" height="350" fill="#FAFAFA"/><text x="250" y="35" font-family="Georgia, serif" font-size="18" fill="${c.primary}" text-anchor="middle" font-weight="600">HISTORICAL TIMELINE</text><line x1="60" y1="50" x2="440" y2="50" stroke="${c.accent}" stroke-width="2"/><line x1="100" y1="180" x2="400" y2="180" stroke="${c.primary}" stroke-width="3"/><rect x="85" y="${180-h1}" width="30" height="${h1}" fill="${c.accent}" opacity="0.6"/><rect x="185" y="${180-h2}" width="30" height="${h2}" fill="${c.tertiary}" opacity="0.6"/><rect x="285" y="${180-h3}" width="30" height="${h3}" fill="${c.accent}" opacity="0.6"/><rect x="385" y="${180-h4}" width="30" height="${h4}" fill="${c.tertiary}" opacity="0.6"/><circle cx="100" cy="180" r="8" fill="${c.accent}" stroke="${c.primary}" stroke-width="2"/><circle cx="200" cy="180" r="8" fill="${c.tertiary}" stroke="${c.primary}" stroke-width="2"/><circle cx="300" cy="180" r="8" fill="${c.accent}" stroke="${c.primary}" stroke-width="2"/><circle cx="400" cy="180" r="8" fill="${c.tertiary}" stroke="${c.primary}" stroke-width="2"/><text x="100" y="210" font-family="Arial" font-size="11" fill="${c.primary}" text-anchor="middle">Early</text><text x="200" y="210" font-family="Arial" font-size="11" fill="${c.primary}" text-anchor="middle">Growth</text><text x="300" y="210" font-family="Arial" font-size="11" fill="${c.primary}" text-anchor="middle">Peak</text><text x="400" y="210" font-family="Arial" font-size="11" fill="${c.primary}" text-anchor="middle">Legacy</text><text x="250" y="310" font-family="Georgia, serif" font-size="11" fill="#888" text-anchor="middle" font-style="italic">Fig. 1: Chronological phases</text></svg>`)}`;
    },
    hierarchy: () => {
      const offset = variation % 10;
      return `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 350"><rect width="500" height="350" fill="#FAFAFA"/><text x="250" y="35" font-family="Georgia, serif" font-size="18" fill="${c.primary}" text-anchor="middle" font-weight="600">HIERARCHICAL STRUCTURE</text><line x1="60" y1="50" x2="440" y2="50" stroke="${c.accent}" stroke-width="2"/><rect x="200" y="${75+offset}" width="100" height="45" fill="${c.accent}" fill-opacity="0.3" stroke="${c.primary}" stroke-width="2.5" rx="5"/><text x="250" y="${103+offset}" font-family="Arial" font-size="13" fill="${c.primary}" text-anchor="middle" font-weight="600">Leadership</text><line x1="250" y1="${120+offset}" x2="250" y2="155" stroke="${c.primary}" stroke-width="2.5"/><rect x="${90+offset}" y="155" width="80" height="38" fill="${c.tertiary}" fill-opacity="0.2" stroke="${c.primary}" stroke-width="2" rx="4"/><text x="${130+offset}" y="178" font-family="Arial" font-size="11" fill="${c.primary}" text-anchor="middle">Division A</text><rect x="210" y="155" width="80" height="38" fill="${c.tertiary}" fill-opacity="0.2" stroke="${c.primary}" stroke-width="2" rx="4"/><text x="250" y="178" font-family="Arial" font-size="11" fill="${c.primary}" text-anchor="middle">Division B</text><rect x="${330-offset}" y="155" width="80" height="38" fill="${c.tertiary}" fill-opacity="0.2" stroke="${c.primary}" stroke-width="2" rx="4"/><text x="${370-offset}" y="178" font-family="Arial" font-size="11" fill="${c.primary}" text-anchor="middle">Division C</text><line x1="250" y1="${120+offset}" x2="${130+offset}" y2="155" stroke="${c.primary}" stroke-width="2"/><line x1="250" y1="${120+offset}" x2="${370-offset}" y2="155" stroke="${c.primary}" stroke-width="2"/><text x="250" y="310" font-family="Georgia, serif" font-size="11" fill="#888" text-anchor="middle" font-style="italic">Fig. 2: Organizational hierarchy</text></svg>`)}`;
    },
    flowchart: () => {
      return `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 350"><rect width="500" height="350" fill="#FAFAFA"/><text x="250" y="35" font-family="Georgia, serif" font-size="18" fill="${c.primary}" text-anchor="middle" font-weight="600">PROCESS FLOW</text><line x1="60" y1="50" x2="440" y2="50" stroke="${c.accent}" stroke-width="2"/><rect x="200" y="70" width="100" height="40" fill="${c.accent}" fill-opacity="0.3" stroke="${c.primary}" stroke-width="2" rx="20"/><text x="250" y="95" font-family="Arial" font-size="12" fill="${c.primary}" text-anchor="middle">Start</text><line x1="250" y1="110" x2="250" y2="130" stroke="${c.primary}" stroke-width="2"/><path d="M 200 155 L 250 135 L 300 155 L 250 175 Z" fill="${c.tertiary}" fill-opacity="0.3" stroke="${c.primary}" stroke-width="2"/><text x="250" y="160" font-family="Arial" font-size="11" fill="${c.primary}" text-anchor="middle">Decision</text><line x1="250" y1="175" x2="250" y2="195" stroke="${c.primary}" stroke-width="2"/><rect x="200" y="195" width="100" height="40" fill="${c.accent}" fill-opacity="0.3" stroke="${c.primary}" stroke-width="2" rx="5"/><text x="250" y="220" font-family="Arial" font-size="11" fill="${c.primary}" text-anchor="middle">Action</text><line x1="250" y1="235" x2="250" y2="255" stroke="${c.primary}" stroke-width="2"/><rect x="200" y="255" width="100" height="30" fill="${c.tertiary}" fill-opacity="0.3" stroke="${c.primary}" stroke-width="2" rx="15"/><text x="250" y="275" font-family="Arial" font-size="11" fill="${c.primary}" text-anchor="middle">End</text><text x="250" y="325" font-family="Georgia, serif" font-size="11" fill="#888" text-anchor="middle" font-style="italic">Fig. 3: Process flowchart</text></svg>`)}`;
    },
    network: () => {
      return `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 350"><rect width="500" height="350" fill="#FAFAFA"/><text x="250" y="35" font-family="Georgia, serif" font-size="18" fill="${c.primary}" text-anchor="middle" font-weight="600">NETWORK STRUCTURE</text><line x1="60" y1="50" x2="440" y2="50" stroke="${c.accent}" stroke-width="2"/><circle cx="250" cy="150" r="35" fill="${c.accent}" fill-opacity="0.3" stroke="${c.primary}" stroke-width="2.5"/><text x="250" y="155" font-family="Arial" font-size="12" fill="${c.primary}" text-anchor="middle" font-weight="600">Core</text><circle cx="150" cy="100" r="25" fill="${c.tertiary}" fill-opacity="0.3" stroke="${c.primary}" stroke-width="2"/><text x="150" y="105" font-family="Arial" font-size="10" fill="${c.primary}" text-anchor="middle">Node 1</text><circle cx="350" cy="100" r="25" fill="${c.tertiary}" fill-opacity="0.3" stroke="${c.primary}" stroke-width="2"/><text x="350" y="105" font-family="Arial" font-size="10" fill="${c.primary}" text-anchor="middle">Node 2</text><circle cx="150" cy="220" r="25" fill="${c.tertiary}" fill-opacity="0.3" stroke="${c.primary}" stroke-width="2"/><text x="150" y="225" font-family="Arial" font-size="10" fill="${c.primary}" text-anchor="middle">Node 3</text><circle cx="350" cy="220" r="25" fill="${c.tertiary}" fill-opacity="0.3" stroke="${c.primary}" stroke-width="2"/><text x="350" y="225" font-family="Arial" font-size="10" fill="${c.primary}" text-anchor="middle">Node 4</text><line x1="225" y1="130" x2="175" y2="110" stroke="${c.accent}" stroke-width="2" stroke-dasharray="5,5"/><line x1="275" y1="130" x2="325" y2="110" stroke="${c.accent}" stroke-width="2" stroke-dasharray="5,5"/><line x1="225" y1="170" x2="175" y2="210" stroke="${c.accent}" stroke-width="2" stroke-dasharray="5,5"/><line x1="275" y1="170" x2="325" y2="210" stroke="${c.accent}" stroke-width="2" stroke-dasharray="5,5"/><text x="250" y="310" font-family="Georgia, serif" font-size="11" fill="#888" text-anchor="middle" font-style="italic">Fig. 4: Interconnected network</text></svg>`)}`;
    },
    pyramid: () => {
      return `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 350"><rect width="500" height="350" fill="#FAFAFA"/><text x="250" y="35" font-family="Georgia, serif" font-size="18" fill="${c.primary}" text-anchor="middle" font-weight="600">HIERARCHICAL PYRAMID</text><line x1="60" y1="50" x2="440" y2="50" stroke="${c.accent}" stroke-width="2"/><polygon points="250,80 300,120 200,120" fill="${c.accent}" fill-opacity="0.4" stroke="${c.primary}" stroke-width="2"/><text x="250" y="110" font-family="Arial" font-size="11" fill="${c.primary}" text-anchor="middle" font-weight="600">Top</text><polygon points="180,120 320,120 340,170 160,170" fill="${c.tertiary}" fill-opacity="0.3" stroke="${c.primary}" stroke-width="2"/><text x="250" y="150" font-family="Arial" font-size="11" fill="${c.primary}" text-anchor="middle">Middle</text><polygon points="140,170 360,170 380,230 120,230" fill="${c.accent}" fill-opacity="0.3" stroke="${c.primary}" stroke-width="2"/><text x="250" y="205" font-family="Arial" font-size="11" fill="${c.primary}" text-anchor="middle">Base</text><polygon points="100,230 400,230 420,270 80,270" fill="${c.tertiary}" fill-opacity="0.2" stroke="${c.primary}" stroke-width="2"/><text x="250" y="255" font-family="Arial" font-size="11" fill="${c.primary}" text-anchor="middle">Foundation</text><text x="250" y="310" font-family="Georgia, serif" font-size="11" fill="#888" text-anchor="middle" font-style="italic">Fig. 5: Pyramid structure</text></svg>`)}`;
    },
    circular: () => {
      return `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 350"><rect width="500" height="350" fill="#FAFAFA"/><text x="250" y="35" font-family="Georgia, serif" font-size="18" fill="${c.primary}" text-anchor="middle" font-weight="600">CYCLICAL PROCESS</text><line x1="60" y1="50" x2="440" y2="50" stroke="${c.accent}" stroke-width="2"/><circle cx="250" cy="165" r="80" fill="none" stroke="${c.primary}" stroke-width="3" stroke-dasharray="10,5"/><circle cx="250" cy="95" r="20" fill="${c.accent}" fill-opacity="0.4" stroke="${c.primary}" stroke-width="2"/><text x="250" y="100" font-family="Arial" font-size="10" fill="${c.primary}" text-anchor="middle">Phase 1</text><circle cx="320" cy="165" r="20" fill="${c.tertiary}" fill-opacity="0.4" stroke="${c.primary}" stroke-width="2"/><text x="320" y="170" font-family="Arial" font-size="10" fill="${c.primary}" text-anchor="middle">Phase 2</text><circle cx="250" cy="235" r="20" fill="${c.accent}" fill-opacity="0.4" stroke="${c.primary}" stroke-width="2"/><text x="250" y="240" font-family="Arial" font-size="10" fill="${c.primary}" text-anchor="middle">Phase 3</text><circle cx="180" cy="165" r="20" fill="${c.tertiary}" fill-opacity="0.4" stroke="${c.primary}" stroke-width="2"/><text x="180" y="170" font-family="Arial" font-size="10" fill="${c.primary}" text-anchor="middle">Phase 4</text><text x="250" y="310" font-family="Georgia, serif" font-size="11" fill="#888" text-anchor="middle" font-style="italic">Fig. 6: Continuous cycle</text></svg>`)}`;
    },
    comparison: () => {
      const v1 = 40 + (variation % 50), v2 = 60 + ((variation * 2) % 45);
      return `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 350"><rect width="500" height="350" fill="#FAFAFA"/><text x="250" y="35" font-family="Georgia, serif" font-size="18" fill="${c.primary}" text-anchor="middle" font-weight="600">COMPARATIVE ANALYSIS</text><line x1="60" y1="50" x2="440" y2="50" stroke="${c.accent}" stroke-width="2"/><line x1="250" y1="70" x2="250" y2="270" stroke="${c.primary}" stroke-width="2"/><text x="150" y="90" font-family="Arial" font-size="13" fill="${c.primary}" text-anchor="middle" font-weight="600">Category A</text><text x="350" y="90" font-family="Arial" font-size="13" fill="${c.primary}" text-anchor="middle" font-weight="600">Category B</text><rect x="100" y="${250-v1}" width="100" height="${v1}" fill="${c.accent}" fill-opacity="0.5" stroke="${c.primary}" stroke-width="1.5"/><text x="150" y="${245-v1}" font-family="Arial" font-size="10" fill="${c.primary}" text-anchor="middle">Metric 1</text><rect x="300" y="${250-v2}" width="100" height="${v2}" fill="${c.tertiary}" fill-opacity="0.5" stroke="${c.primary}" stroke-width="1.5"/><text x="350" y="${245-v2}" font-family="Arial" font-size="10" fill="${c.primary}" text-anchor="middle">Metric 1</text><line x1="90" y1="250" x2="410" y2="250" stroke="${c.primary}" stroke-width="2"/><text x="250" y="310" font-family="Georgia, serif" font-size="11" fill="#888" text-anchor="middle" font-style="italic">Fig. 7: Comparison chart</text></svg>`)}`;
    },
    process: () => {
      return `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 350"><rect width="500" height="350" fill="#FAFAFA"/><text x="250" y="35" font-family="Georgia, serif" font-size="18" fill="${c.primary}" text-anchor="middle" font-weight="600">SEQUENTIAL PROCESS</text><line x1="60" y1="50" x2="440" y2="50" stroke="${c.accent}" stroke-width="2"/><rect x="50" y="100" width="80" height="50" fill="${c.accent}" fill-opacity="0.3" stroke="${c.primary}" stroke-width="2" rx="5"/><text x="90" y="130" font-family="Arial" font-size="11" fill="${c.primary}" text-anchor="middle">Input</text><line x1="130" y1="125" x2="165" y2="125" stroke="${c.primary}" stroke-width="2"/><rect x="165" y="100" width="80" height="50" fill="${c.tertiary}" fill-opacity="0.3" stroke="${c.primary}" stroke-width="2" rx="5"/><text x="205" y="130" font-family="Arial" font-size="11" fill="${c.primary}" text-anchor="middle">Process</text><line x1="245" y1="125" x2="280" y2="125" stroke="${c.primary}" stroke-width="2"/><rect x="280" y="100" width="80" height="50" fill="${c.accent}" fill-opacity="0.3" stroke="${c.primary}" stroke-width="2" rx="5"/><text x="320" y="130" font-family="Arial" font-size="11" fill="${c.primary}" text-anchor="middle">Analyze</text><line x1="360" y1="125" x2="395" y2="125" stroke="${c.primary}" stroke-width="2"/><circle cx="430" cy="125" r="25" fill="${c.tertiary}" fill-opacity="0.3" stroke="${c.primary}" stroke-width="2"/><text x="430" y="130" font-family="Arial" font-size="10" fill="${c.primary}" text-anchor="middle">Output</text><text x="250" y="310" font-family="Georgia, serif" font-size="11" fill="#888" text-anchor="middle" font-style="italic">Fig. 8: Sequential process</text></svg>`)}`;
    }
  };
  
  return generators[selectedType]();
};
